language: java
jdk:
- oraclejdk8
install:
- "sh ./build-with-dependencies.sh"
after_success:
- "./gradlew coveralls"
env:
  global:
  - secure: nyfgkr66Z4I7m1luRdEMUghO76lpJiHNjFP79rgzEfnS9uXl38s5xazGBKA5oljifvU3c0bBLA2aSFT/0+up8RPv6RdX5Ug3OLlbzGHl7XKIvTTPQNdjsNtN/EKoSr81G+MKcBj5mVpoF+qdY3RJS3PzG5GSB/eIU2CTo1MvrirH3apBG2kHgFeMGFeBIktUzVzjcwrDzOUbHo7n159yIB0Fy7IGg7vJFysa/BPgaW6Ix2pw4LpjJn46Qbvc+ZOXeeZ7wBMO4Y4fdUMhj2QeJyCdS8ZQAwb6ZyG5InD8YEAxy6wzwH3S410fB5LjeWLmHd7dVPCLPBxqkG8lO2xMBoWpoxLATHAhpap0gwbni0GvjjMs/GNe+hHbfSj6qNXsj36Hd/NJWVFKZu6gAVtwcAj6d3fkG8riWcDfj2Pe2jfTegFl81j0EAnLYyLJ/UsBeupRqpTuc+NrchceC0axa8QW+rohj/Pzxm3gq/T7MgFceSxdlSA0GL/vQanKfC4YUMpMlqOQKs4EL46DvNsIQUf5HAt4jcfKrVmPHPM5HyDWHG/aoVDP9tlKeI8g5ZEr0kcXuv4+NOzWjznTxM+pxOcFAzL9vUz1q8NQ9P0Wdhvl6MvlbnTInVsbhhEDNZ6+cAPheqpHP78M5M+Vv7hw7ZcnSvt0fo8xFvsOmwpWXMQ=
